version: '3'
services:
  mongo-db:
    container_name: PFA-MongoDB-Container
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    restart: always
    ports:
      - '27017:27017'
